title: Rowan's Site
description: Demonstrating industry knowledge, coding and project experiences
theme: just-the-docs

url: https://rlaw23.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
