title: Rowan's Site
description: Industry knowledge, coding and projects
theme: just-the-docs

url: https://rlaw23.github.io

# aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
